
  <H2 align="center"> INSERTE SUS DATOS DEL AULA </H2>
  <form method="post"  >

<div align="center">
      
       <table width="60%" border="0" cellspacing="1" cellpadding="1">
         <tr>
           <th scope="col"><div align="left"><a href="<?php echo $this->baseUrl();?>/admin/aula/listaraula"><img src="http://localhost/proyecto1/public/editar/publicar.jpg" width="35" height="35" />Listar Aula</a> </div></th>
           <th scope="col">&nbsp;</th>
           <th scope="col">&nbsp;</th>
         </tr>
       </table>
       <table id="table2" width="60%" height="33" border="0" cellpadding="2" cellspacing="1">
    <tr>
      <td width="150"><div align="right"><strong>N&deg; Aula </strong></div></td>
      <td width="50"><?php echo  $this->form->nombre;?></td>
      <td width="207"><div align="right"><strong>Descripcion : </strong></div></td>
      <td width="50"><?php echo  $this->form->apellido;?></td>
       <td width="207"><div align="right"><strong>Descripcion : </strong></div></td>
      <td width="50"><?php echo  $this->form->correo;?></td>
      <td width="139"><div align="center"><strong>Fecha : </strong></div></td>
    
    </tr>
 
    
    
  </table>
  
    
  </div>
</form>    

    
    
    
    
    
    
    



     
 
    

     
    
  
