<h1>
    Bienvenidos a la vista registro <br>
    de la funcion registroAction del <br>
    controlador UsuarioController <br>
    <hr>
     <?php echo $this->titulo; ?>
   
</h1>
<hr />
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttributes(array(
        'action'=>$this->url.'/admin/usuario/registro',
        'method'=>'post'
    ));
    // Get the form label plugin
    $formLabel = $this->plugin('formLabel');

    // Render the opening tag
    echo $this->form()->openTag($form);
    ?>
    <?php
    if(!empty($this->id))
    {
     ?>
    <p style="color: greenyellow;">El registro se guardo correctamente</p>
    <?php
        }
     ?>

    <div class="form_element">
    <?php
    $name = $form->get('nombre');
    echo $formLabel->openTag().$name->getOption('label');
    echo $this->formElementErrors($name);
    echo $formLabel->closeTag()."<br>";
    echo $this->formInput($name);
    ?>
    </div>
    
    <div class="form_element">
    <?php
    $namesd = $form->get('apellido');
    echo $formLabel->openTag().$namesd->getOption('label');
    echo $this->formElementErrors($namesd);
    echo $formLabel->closeTag()."<br>";
    echo $this->formInput($namesd);
    ?>
    </div>
    
     <div class="form_element">
    <?php
    $apellido_m = $form->get('apellido_m');
    echo $formLabel->openTag().$apellido_m->getOption('label');
    echo $this->formElementErrors($apellido_m);
    echo $formLabel->closeTag()."<br>";
    echo $this->formInput($apellido_m);
    ?>
    </div>

    <div class="form_element">
    <?php
    $email = $form->get('correo');
    echo $formLabel->openTag().$email->getOption('label');
//    echo $this->formElementErrors($email);
    echo $formLabel->closeTag()."<br>";
    echo $this->formInput($email);
    ?>
    </div>
      
     

    <?php echo $this->formElement($form->get('send')) ?>

    <?php echo $this->form()->closeTag() ?>
