
<!-- ////////////////////////////////tables///////////////////////////////////////////////////////////////////// -->
<!--<link href="http://localhost/ventas/public/DataTables_filtos/media/css/demo_page.css" rel="stylesheet" type="text/css" media="screen" />-->
		<link href="http://localhost/ventas/public/DataTables_filtos/media/css/demo_table_jui.css" rel="stylesheet" type="text/css" media="screen" />
		<link href="http://localhost/ventas/public/DataTables_filtos/media_extras/css/TableTools_JUI.css" rel="stylesheet" type="text/css" media="screen" />
		<link href="http://localhost/ventas/public/DataTables_filtos/examples_support/themes/smoothness/jquery-ui-1.8.4.custom.css" rel="stylesheet" type="text/css" media="screen" />
		
		<script type="text/javascript" charset="utf-8" src="http://localhost/ventas/public/DataTables_filtos/media/js/jquery.js"></script>
		<script type="text/javascript" charset="utf-8" src="http://localhost/ventas/public/DataTables_filtos/media/js/jquery.dataTables.js"></script>
		<script type="text/javascript" charset="utf-8" src="http://localhost/ventas/public/DataTables_filtos/media_extras/js/ZeroClipboard.js"></script>
		<script type="text/javascript" charset="utf-8" src="http://localhost/ventas/public/DataTables_filtos/media_extras/js/TableTools.js"></script>
		<script type="text/javascript" charset="utf-8">
			$(document).ready( function () {
				$('#example').dataTable( {
					"bJQueryUI": true,
					"sPaginationType": "full_numbers",
//					"sDom": '<"H"Tfr>t<"F"ip>',
					"oTableTools": {"sSwfPath": "http://localhost/ventas/public/DataTables_filtos/media_extras/swf/copy_cvs_xls_pdf.swf",
						"aButtons": [
							"copy", "csv", "xls", "pdf",
							{
								"sExtends":    "collection",
								"sButtonText": "Save",
								"aButtons":    [ "csv", "xls", "pdf" ]
							}
						]
					}
				} );
			} );
		</script>
<body id="dt_example">
<br>
		<div id="container"><span id="container">
	    <div class="titulo" align="center"></div>
		
		<a href="<?php  echo $this->basePath()?>/admin/articulos/registro">nuevo</a> 
                    </span>
		  <div id="demo">
                      <center>
                      <h4>LISTA DE ARTICULOS</h4>
		  <table width="55%" border="0"  cellpadding="0" cellspacing="0" class="display" id="example">
 <thead> 
  <tr>
     <th width="50" align="center">Nro</th>
     <th width="95">CODIGO</th>
     <th width="119">ARTICULO </th>
     <th width="70" align="center">DESCRIPCION</th>
     <th width="70" align="center">Precio_Compra</th>
     <th width="70" align="center">Precio_Venta</th>
     <th width="70" align="center">Cantidad_Stock</th>
     <th width="70" align="center">Fecha</th>
     <th width="254" align="center">OPCIONES</th>
  </tr>
  </thead>
  <tfoot>
 </tfoot>
<tbody>
	
  <?php
 $n=0;
  	foreach ($this->datos as $value)
       
	 {  $n++; ?>
	
	
  <tr class="gradeA">

  <td align="center"><?= $n ?></td>
    <td><?= $value['codigo']; ?></td>
    <td><?= $value['nombre']; ?></td>
      <td><?= $value['descripcion']; ?></td>
    <td><?= $value['precio_compra']; ?></td>
    <td><?= $value['precio_venta']; ?></td>
    <td><?= $value['cantidad_stock']; ?></td>
    <td><?= $value['fecha_reg']; ?></td>
    <td>
	  
        
        
     
        <a href="<?php
               echo $this->basePath()?>/admin/articulos/eliminar/<?php echo $value['id_articulos']
                ?> " onclick ="return confirm('&iquest;Esta Seguro Dar de Alta al <?php echo $value['nombre']; ?>?')"><font color="red"><img src="http://localhost/proyecto1/public/editar/b_drop.png" alt="dd" width="16" height="16">Dar De Alta</font> </a>
               
   

 
            <a href="<?php  echo $this->basePath()?>/admin/usuario/eliminar/<?php echo $value['id']?>">ver</a>        
        
 
	   </td>
	   
              <?php  }?>
  </tr>
  </tbody>
</table>
</div>
		</div>
	
	</body>

